CIPHER_FREQUENCIES_OUTPUT = 'cipher_frequencies.json'
CIPHER_TEXT_PATH = 'cod4.txt'
DECRYPTED_TEXT_OUTPUT = 'cod4_decrypted.txt'
MAPPING_OUTPUT = 'mapping.json'
RUSSIAN_FREQUENCIES_PATH = 'russian_letter_frequency.json'
